### ISSUE TITLE
✓ Ampalibe. TODO List

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Ampalibe#20]
This is the list that contains all ideas about Ampalibe.

## FEATURES

- [x] MongoDB Support
- [x] Items length for quick reply
- [x] Hot reload
- [x] Multi Langage Management
- [x] Customize Text for Next and More bouton in template and quick_reply 
- [x] ADD [Receipt Template](https://developers.facebook.com/docs/messenger-platform/reference/templates/receipt)
- [x] [Personas Management](https://developers.facebook.com/docs/messenger-platform/reference/personas-api)

## COMMAND LINE

- [x] Decorate script ampalibe for windows like Linux
- [x] Add a command to init only env file 
      
     > Windows & Linux doesn't have same .env file format 

## IMPROVEMENTS

- [x] Add Element Object to generate Element JSON
- [x] ADD Quick Rep Object to generate quick repl JSON
- [x] ADD kwargs for Messenger API to configure other parameters

## AUTOMATION

- [x] Unit Test
- [x] Auto Release on Pypi
